module.exports = {

    RETRIEMENT_PAGE_CAGE: 30,
    RETRIEMENT_PAGE_RETIREAGE: 60,   
    RETRIEMENT_PAGE_CINCOME: '$400',
    RETRIEMENT_PAGE_SAVING_BAL: '$5000',
    RETRIEMENT_PAGE_SAVING_EACH_YR: 20,
    RETRIEMENT_PAGE_INCRESE_ECH_YR: 9,
    RETRIEMENT_PAGE_SS_OVERRIDE_AMOUNT: '$7000',    
    RETRIEMENT_PAGE_SP_INCOME: '$4000',
    ADJUST_DEFAULT_PAGE_YR_DEP : 5,
    SOCIAL_SECURIT_BENEFIT_YES: true,
    SOCIAL_SECURIT_BENEFIT_NO: false,
    RETRIEMENT_PAGE_PATH_URI: 'retirement-calculator.html',
    COMMON_SCR_PATH: '../Temp/abc.png',

}